export const data = [
    {
        F1:"1",
        F2:"You can’t go back and change the beginning, but you can start where you are and change the ending"
    },
    {
        F1:"Unknown",
        F2:"Convince yourself that you have the power to be all what you wish to be. It is YOU who could generate in you a huge power of motivation to push you forward and ignite you to think and to do."
    },
    {
        F1:"3",
        F2:"Happiness is not the absence of problems, it’s the ability to deal with them."
    },
    {
        F1:"4",
        F2:"cool people"
    },
    {
        F1:"5",
        F2:"The most precious gift we can offer others is our presence. When our mindfulness embraces those we love, they will bloom like flowers."
    },
    {
        F1:"6",
        F2:"Miracles start to happen when you give as much energy to your dreams as you do to your fears."
    },
    {
        F1:"7", 
        F2:"If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you." 
    },
    {F1:"8", F2:"Don’t be upset with people and situations in your life, because both are powerless without your reaction. " },
    {F1:"9", F2:" Be patient. Empires are not built in a day" },
    {F1:"10", F2:"Never perceive anything as being inevitable or predestined. The only absolute is uncertainty. " },
    {F1:"11", F2:"The truest indication of gratitude is to return what you are grateful for. " },
    {F1:"12", F2:" There’s no need to rush. What’s meant for you always arrives right on time." },
    {F1:"13", F2:"Happiness lies in the joy of achievement and the thrill of creative effort. " },
    {F1:"14", F2:" Happiness lies in the joy of achievement and the thrill of creative effort." },
    {F1:"15", F2:" Find the sweetness in your own heart so that you may find the sweetness in every Heart!" },
    {F1:"16", F2:" Open your eyes to the beauty around you, Open your mind to the wonders of life, Open your heart to those who love you, And always be true to yourself." },
    {F1:"17", F2:" For everything you have lost, you have gained something else." },
    {F1:"18", F2:"A failure establishes only this, that our determination to succeed was not strong enough. " },
    {F1:"19", F2:"Doing what you like is freedom. Liking what you do is happiness. " },
    {F1:"20", F2:" The universe will often give you what you truly desire, even when you didn’t realize it was what you were truly wanting." },
    {F1:"21", F2:" We have a ‘strategic’ plan. It’s called doing things." },
    {F1:"22", F2:"Your future is created by what you do today, not tomorrow. " },
    {F1:"23", F2:"Your future is created by what you do today, not tomorrow. " },
    {F1:"24", F2:" The best preparation for tomorrow is doing your best today. " },
    {F1:"25", F2:" It is during our darkest moments that we must focus to see the" },
    {F1:"26", F2:"I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.  " },
    {F1:"27", F2:" The most difficult thing is the decision to act, the rest is merely tenacity. " },
    {F1:"28", F2:" Life is what happens to you while you’re busy making other plans. " },
    {F1:"29", F2:" Success is not final; failure is not fatal: It is the courage to continue that counts" },
    {F1:"30", F2:"The road to success and the road to failure are almost exactly the same " },
    {F1:"31", F2:" Success usually comes to those who are too busy to be looking for it" },
    {F1:"32", F2:"Opportunities don’t happen. You create them. " },
    {F1:"33", F2:"Don’t be afraid to give up the good to go for the great." },
    {F1:"34", F2:" I find that the harder I work, the more luck I seem to have" },
    {F1:"35", F2:"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed " },
    {F1:"36", F2:" Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better" },
    {F1:"37", F2:"Never give in except to convictions of honor and good sense." },
    {F1:"38", F2:" Stop chasing the money and start chasing the passion😉" },
    {F1:"39", F2:"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race " },
    {F1:"40", F2:" There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind" },
    {F1:"41", F2:"There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind " },
    {F1:"42", F2:"Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable " },
    {F1:"43", F2:"I never dreamed about success. I worked for it " },
    {F1:"44", F2:" Success is getting what you want, happiness is wanting what you get" },
    {F1:"45", F2:" Success is walking from failure to failure with no loss of enthusiasm." },
    {F1:"46", F2:"Success is walking from failure to failure with no loss of enthusiasm. " },
    {F1:"47", F2:"Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success. " },
    {F1:"48", F2:" There are no secrets to success. It is the result of preparation, hard work, and learning from failure." },
    {F1:"49", F2:" Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit." },
    {F1:"50", F2:" If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse" },
    {F1:"51", F2:" I cannot give you the formula for success, but I can give you the formula for failure – It is: Try to please everybody." },
    {F1:"52", F2:" Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." },
    {F1:"53", F2:" Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do." },
    {F1:"54", F2:" Some people dream of success while others wake up and work" },
    {F1:"55", F2:"he difference between who you are and who you want to be is what you do. " },
    {F1:"56", F2:"In order to succeed, your desire for success should be greater than your fear of failure. " },
    {F1:"57", F2:"In order to succeed, we must first believe that we can." },
    {F1:"58", F2:"Dreams don’t work unless you do. " },
    {F1:"59", F2:"Go the extra mile. It’s never crowded there " },
    {F1:"60", F2:"Keep your face always toward the sunshine – and shadows will fall behind you " },
    {F1:"61", F2:"What defines us is how well we rise after falling. " },
    {F1:"62", F2:"Hold On. Pain Ends. " },
    {F1:"63", F2:" Make each day your masterpiece. " },
    {F1:"64", F2:" We can do anything we want to if we stick to it long enough." },
    {F1:"65", F2:"Many of life’s failures are people who did not realize how close they were to success when they gave up " },
    {F1:"66", F2:"Don’t be distracted by criticism. Remember–the only taste of success some people get is to take a bite out of you. " },
    {F1:"67", F2:"The secret of success is to do the common thing uncommonly well " },
    {F1:"68", F2:" You know you are on the road to success if you would do your job, and not be paid for it" },
    {F1:"69", F2:" I never did anything worth doing by accident, nor did any of my inventions come indirectly through accident, except the phonograph. No, when I have fully decided that a result is worth getting, I go about it, and make trial after trial, until it comes" },
    {F1:"70", F2:"There is a powerful driving force inside every human being that, once unleashed, can make any vision, dream, or desire a reality " },
    {F1:"71", F2:" The secret to success is to know something nobody else knows" },
    {F1:"72", F2:" Your life only gets better when you get better." },
    {F1:"73", F2:" Happiness is not by chance, but by choice." },
    {F1:"74", F2:"If I cannot do great things, I can do small things in a great way " },
    {F1:"75", F2:"We generate fears while we sit. We overcome them by action. " },
    {F1:"76", F2:" The bad news is time flies. The good news is you’re the pilot" },
    {F1:"77", F2:" Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination." },
    {F1:"78", F2:" What’s on the other side of fear? Nothing." },
    {F1:"79", F2:" Quitters never win. Winners never quit!" },
    {F1:"80", F2:" It’s not your salary that makes you rich, it’s your spending habits." },
    {F1:"81", F2:"It’s never too late for a new beginning in your life. " },
    {F1:"82", F2:"If opportunity doesn’t knock build a door " },
    {F1:"83", F2:" It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest." },
    {F1:"84", F2:" If you’ve never eaten while crying you don’t know what life tastes like" },
    {F1:"85", F2:"We can see through others only when we can see through ourselves." },
    {F1:"86", F2:"You don’t get paid for the hour. You get paid for the value you bring to the hour" },
    {F1:"87", F2:" The best way to get started is to quit talking and begin doing" },
    {F1:"88", F2:"There are no limits to what you can accomplish, except the limits you place on your own thinking " },
    {F1:"89", F2:"Hard work beats talent when talent doesn’t work hard. " },
    {F1:"90", F2:"If everything seems to be under control, you’re not going fast enough. " },
    {F1:"91", F2:" Opportunity is missed by most people because it is dressed in overalls and looks like work" },
    {F1:"92", F2:"Go as far as you can see; when you get there, you’ll be able to see further " },
    {F1:"93", F2:"Your talent determines what you can do. Motivation determines how much you’re willing to do. Your attitude determines how well you do it " },
    {F1:"94", F2:"A year from now you may wish you had started today." },
    {F1:"95", F2:"Light tomorrow with today. " },
    {F1:"96", F2:"Don’t count the days, make the days count. " },
    {F1:"97", F2:"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success." },
    {F1:"98", F2:" Failure is the condiment that gives success its flavor" },
    {F1:"99", F2:" Success only comes to those who dare to attempt" },
    {F1:"100", F2:" The elevator to success is out of order. You’ll have to use the stairs, one step at a time" },
    {F1:"101", F2:" The secret was to just be cool, stay in God's graces, and work it out." },
    {F1:"102", F2:" Forget the failures. Keep the lessons." },
    {F1:"103", F2:" If you can't change your fate, change your attitude." },
    {F1:"104", F2:" Animals are such agreeable friends - they ask no questions; they pass no criticisms." },
    {F1:"105", F2:" I can take it. The tougher it gets, the cooler I get." },
    {F1:"106", F2:"et you can't learn to be cool, it's more a personality trait. " },
    {F1:"107", F2:" If you really want something, you can figure out how to make it happen" },
    {F1:"108", F2:"Any fool can write code that a computer can understand. Good programmers write code that humans can understand. " },
    {F1:"109", F2:"First, solve the problem. Then, write the code. " },
    {F1:"110", F2:" Experience is the name everyone gives to their mistakes" },
    {F1:"111", F2:"In order to be irreplaceable, one must always be different " },
    {F1:"112", F2:" Java is to JavaScript what car is to Carpet" },
    {F1:"113", F2:" Knowledge is power" },
    {F1:"114", F2:" Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code." },
    {F1:"115", F2:" Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away." },
    {F1:"116", F2:"Code is like humor. When you have to explain it, it’s bad. " },
    {F1:"117", F2:" Fix the cause, not the symptom" },
    {F1:"118", F2:"Optimism is an occupational hazard of programming: feedback is the treatment. " },
    {F1:"119", F2:" When to use iterative development? You should use iterative development only on projects that you want to succeed." },
    {F1:"120", F2:" Simplicity is the soul of efficiency." },
    {F1:"121", F2:"Before software can be reusable it first has to be usable " },
    {F1:"122", F2:" Make it work, make it right, make it fast." },
    {F1:"123", F2:" Should array indices start at 0 or 1? My compromise of 0.5 was rejected without, I thought, proper consideration." },
    {F1:"124", F2:" Computers are fast; programmers keep it slow." },
    {F1:"125", F2:" When I wrote this code, only God and I understood what I did. Now only God knows" },
    {F1:"126", F2:" A son asked his father (a programmer) why the sun rises in the east, and sets in the west. His response? It works, don’t touch!" },
    {F1:"127", F2:"How many programmers does it take to change a light bulb? None, that’s a hardware problem " },
    {F1:"128", F2:"Programming is like sex: One mistake and you have to support it for the rest of your life. " },
    {F1:"129", F2:" Programming can be fun, and so can cryptography; however, they should not be combined" },
    {F1:"130", F2:" Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning" },
    {F1:"131", F2:" Copy-and-Paste was programmed by programmers for programmers actually" },
    {F1:"132", F2:" Always code as if the person who ends up maintaining your code will be a violent psychopath who knows where you live." },
    {F1:"133", F2:" Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it." },
    {F1:"134", F2:" “Algorithm: Word used by programmers when they don’t want to explain what they did." },
    {F1:"135", F2:" Software and cathedrals are much the same — first we build them, then we pray." },
    {F1:"136", F2:" There are two ways to write error-free programs; only the third works." },
    {F1:"137", F2:" 99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around. 127 little bugs in the code …" },
    {F1:"138", F2:"Remember that there is no code faster than no code. " },
    {F1:"139", F2:"One man’s crappy software is another man’s full-time job. " },
    {F1:"140", F2:" Don’t worry if it doesn’t work right. If everything did, you’d be out of a job" },
    {F1:"141", F2:"It’s not a bug — it’s an undocumented feature " },
    {F1:"142", F2:" In a room full of top software designers, if two agree on the same thing, that’s a majority." },
    {F1:"143", F2:" There are only two kinds of programming languages out there. The ones people complain about and the ones no one uses" },
    {F1:"144", F2:" Learning to write programs stretches your mind, and helps you think better, creates a way of thinking about things that I think is helpful in all domains." },
    {F1:"145", F2:" Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes" },
    {F1:"146", F2:"Before you marry a person, you should first make them use a computer with slow Internet to see who they really are. " },
    {F1:"147", F2:" I love being married. It's so great to find that one special person you want to annoy for the rest of your life" },
    {F1:"148", F2:" I want my children to have all the things I couldn't afford. Then I want to move in with them." },
    {F1:"149", F2:" Ned, I would love to stand here and talk with you—but I’m not going to" },
    {F1:"150", F2:"Insomnia sharpens your math skills because you spend all night calculating how much sleep you’ll get if you’re able to ‘fall asleep right now. " }

    
]